"""sync support models

Revision ID: 076d9f21b4e3
Revises: 20260703_0014
Create Date: 2026-07-03 16:02:48.606758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076d9f21b4e3'
down_revision: Union[str, Sequence[str], None] = '20260703_0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('login_label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('browser_profile_key', sa.String(length=120), nullable=True),
    sa.Column('browser_profile_path', sa.Text(), nullable=True),
    sa.Column('session_status', sa.String(length=40), nullable=True),
    sa.Column('risk_status', sa.String(length=40), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('min_send_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_accounts_account_name'), 'dm_accounts', ['account_name'], unique=False)
    op.create_index(op.f('ix_dm_accounts_platform'), 'dm_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_dm_accounts_risk_status'), 'dm_accounts', ['risk_status'], unique=False)
    op.create_index(op.f('ix_dm_accounts_session_status'), 'dm_accounts', ['session_status'], unique=False)
    op.create_index(op.f('ix_dm_accounts_status'), 'dm_accounts', ['status'], unique=False)
    op.create_table('dm_platform_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('home_url', sa.String(length=240), nullable=False),
    sa.Column('inbox_url', sa.String(length=240), nullable=False),
    sa.Column('merchant_search_url', sa.String(length=240), nullable=False),
    sa.Column('login_check_selector', sa.String(length=240), nullable=False),
    sa.Column('risk_check_selector', sa.String(length=240), nullable=False),
    sa.Column('merchant_link_selector', sa.String(length=240), nullable=False),
    sa.Column('message_button_selector', sa.String(length=240), nullable=False),
    sa.Column('input_selector', sa.String(length=240), nullable=False),
    sa.Column('send_button_selector', sa.String(length=240), nullable=False),
    sa.Column('sent_success_selector', sa.String(length=240), nullable=False),
    sa.Column('unread_selector', sa.String(length=240), nullable=False),
    sa.Column('conversation_item_selector', sa.String(length=240), nullable=False),
    sa.Column('conversation_title_selector', sa.String(length=240), nullable=False),
    sa.Column('message_text_selector', sa.String(length=240), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_platform_configs_platform'), 'dm_platform_configs', ['platform'], unique=False)
    op.create_table('dm_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_templates_name'), 'dm_templates', ['name'], unique=False)
    op.create_index(op.f('ix_dm_templates_platform'), 'dm_templates', ['platform'], unique=False)
    op.create_table('learning_experiments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('success_metric', sa.String(length=120), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_experiments_name'), 'learning_experiments', ['name'], unique=False)
    op.create_index(op.f('ix_learning_experiments_status'), 'learning_experiments', ['status'], unique=False)
    op.create_index(op.f('ix_learning_experiments_target_type'), 'learning_experiments', ['target_type'], unique=False)
    op.create_table('learning_suggestions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('proposed_content', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reviewer', sa.String(length=80), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('rollback_point', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_suggestions_source_record_id'), 'learning_suggestions', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_learning_suggestions_source_type'), 'learning_suggestions', ['source_type'], unique=False)
    op.create_index(op.f('ix_learning_suggestions_status'), 'learning_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_learning_suggestions_target_type'), 'learning_suggestions', ['target_type'], unique=False)
    op.create_index(op.f('ix_learning_suggestions_title'), 'learning_suggestions', ['title'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('date_range', sa.String(length=80), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('requester', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('download_url', sa.String(length=240), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('sensitive_fields_included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_exports_report_type'), 'report_exports', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_exports_requester'), 'report_exports', ['requester'], unique=False)
    op.create_index(op.f('ix_report_exports_status'), 'report_exports', ['status'], unique=False)
    op.create_table('system_audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.String(length=240), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_logs_action'), 'system_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_actor'), 'system_audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_target_id'), 'system_audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_target_type'), 'system_audit_logs', ['target_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('group_key', sa.String(length=40), nullable=False),
    sa.Column('item_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_key', 'item_key', name='uq_system_settings_group_item')
    )
    op.create_index(op.f('ix_system_settings_group_key'), 'system_settings', ['group_key'], unique=False)
    op.create_index(op.f('ix_system_settings_item_key'), 'system_settings', ['item_key'], unique=False)
    op.create_index(op.f('ix_system_settings_label'), 'system_settings', ['label'], unique=False)
    op.create_index(op.f('ix_system_settings_sensitive'), 'system_settings', ['sensitive'], unique=False)
    op.create_index(op.f('ix_system_settings_status'), 'system_settings', ['status'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_name', sa.String(length=80), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('authorization_status', sa.String(length=40), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('fallback_voice', sa.String(length=120), nullable=False),
    sa.Column('consent_material', sa.Text(), nullable=False),
    sa.Column('risk_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_authorization_status'), 'voice_profiles', ['authorization_status'], unique=False)
    op.create_index(op.f('ix_voice_profiles_name'), 'voice_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_voice_profiles_owner_name'), 'voice_profiles', ['owner_name'], unique=False)
    op.create_index(op.f('ix_voice_profiles_scenario'), 'voice_profiles', ['scenario'], unique=False)
    op.create_index(op.f('ix_voice_profiles_status'), 'voice_profiles', ['status'], unique=False)
    op.create_table('comment_intercept_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('keyword', sa.String(length=160), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('video_title', sa.String(length=240), nullable=False),
    sa.Column('owner_account_id', sa.String(length=32), nullable=True),
    sa.Column('sync_status', sa.String(length=40), nullable=False),
    sa.Column('sync_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('keyword_rules', sa.Text(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('human_confirm_required', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_account_id'], ['dm_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_intercept_sources_name'), 'comment_intercept_sources', ['name'], unique=False)
    op.create_index(op.f('ix_comment_intercept_sources_owner_account_id'), 'comment_intercept_sources', ['owner_account_id'], unique=False)
    op.create_index(op.f('ix_comment_intercept_sources_platform'), 'comment_intercept_sources', ['platform'], unique=False)
    op.create_index(op.f('ix_comment_intercept_sources_source_type'), 'comment_intercept_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_comment_intercept_sources_sync_status'), 'comment_intercept_sources', ['sync_status'], unique=False)
    op.create_table('knowledge_base_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('source_suggestion_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_suggestion_id'], ['learning_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_items_category'), 'knowledge_base_items', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_items_source_suggestion_id'), 'knowledge_base_items', ['source_suggestion_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_items_status'), 'knowledge_base_items', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_items_title'), 'knowledge_base_items', ['title'], unique=False)
    op.create_table('voice_samples',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=240), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_samples_profile_id'), 'voice_samples', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voice_samples_quality_status'), 'voice_samples', ['quality_status'], unique=False)
    op.create_table('voice_training_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('sample_minutes', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_training_jobs_profile_id'), 'voice_training_jobs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voice_training_jobs_status'), 'voice_training_jobs', ['status'], unique=False)
    op.create_table('voice_usage_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('merchant_name', sa.String(length=120), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=80), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['outreach_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_usage_records_fallback_used'), 'voice_usage_records', ['fallback_used'], unique=False)
    op.create_index(op.f('ix_voice_usage_records_profile_id'), 'voice_usage_records', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voice_usage_records_result'), 'voice_usage_records', ['result'], unique=False)
    op.create_index(op.f('ix_voice_usage_records_scenario'), 'voice_usage_records', ['scenario'], unique=False)
    op.create_index(op.f('ix_voice_usage_records_task_id'), 'voice_usage_records', ['task_id'], unique=False)
    op.create_table('dm_conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('lead_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('merchant_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('intent_level', sa.String(length=20), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('need_handoff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['dm_accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['merchant_leads.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['outreach_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_conversations_account_id'), 'dm_conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_dm_conversations_intent_level'), 'dm_conversations', ['intent_level'], unique=False)
    op.create_index(op.f('ix_dm_conversations_lead_id'), 'dm_conversations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_dm_conversations_merchant_name'), 'dm_conversations', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_dm_conversations_platform'), 'dm_conversations', ['platform'], unique=False)
    op.create_index(op.f('ix_dm_conversations_status'), 'dm_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_dm_conversations_task_id'), 'dm_conversations', ['task_id'], unique=False)
    op.create_table('intent_customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lead_id', sa.String(length=32), nullable=True),
    sa.Column('merchant_name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('contact_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('intent_level', sa.String(length=20), nullable=False),
    sa.Column('intent_score', sa.Integer(), nullable=False),
    sa.Column('source_channels', sa.String(length=120), nullable=False),
    sa.Column('latest_signal', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=80), nullable=False),
    sa.Column('follow_status', sa.String(length=40), nullable=False),
    sa.Column('next_follow_at', sa.DateTime(), nullable=True),
    sa.Column('need_handoff', sa.Boolean(), nullable=False),
    sa.Column('dnc_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['merchant_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_customers_category'), 'intent_customers', ['category'], unique=False)
    op.create_index(op.f('ix_intent_customers_city'), 'intent_customers', ['city'], unique=False)
    op.create_index(op.f('ix_intent_customers_dnc_status'), 'intent_customers', ['dnc_status'], unique=False)
    op.create_index(op.f('ix_intent_customers_follow_status'), 'intent_customers', ['follow_status'], unique=False)
    op.create_index(op.f('ix_intent_customers_intent_level'), 'intent_customers', ['intent_level'], unique=False)
    op.create_index(op.f('ix_intent_customers_lead_id'), 'intent_customers', ['lead_id'], unique=False)
    op.create_index(op.f('ix_intent_customers_merchant_name'), 'intent_customers', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_intent_customers_need_handoff'), 'intent_customers', ['need_handoff'], unique=False)
    op.create_index(op.f('ix_intent_customers_owner_name'), 'intent_customers', ['owner_name'], unique=False)
    op.create_index(op.f('ix_intent_customers_platform'), 'intent_customers', ['platform'], unique=False)
    op.create_table('social_comments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_comment_id', sa.String(length=120), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('author_profile_url', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('intent_score', sa.Integer(), nullable=False),
    sa.Column('intent_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk_status', sa.String(length=40), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('commented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['comment_intercept_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_comments_author_name'), 'social_comments', ['author_name'], unique=False)
    op.create_index(op.f('ix_social_comments_category'), 'social_comments', ['category'], unique=False)
    op.create_index(op.f('ix_social_comments_city'), 'social_comments', ['city'], unique=False)
    op.create_index(op.f('ix_social_comments_external_comment_id'), 'social_comments', ['external_comment_id'], unique=False)
    op.create_index(op.f('ix_social_comments_intent_level'), 'social_comments', ['intent_level'], unique=False)
    op.create_index(op.f('ix_social_comments_intent_score'), 'social_comments', ['intent_score'], unique=False)
    op.create_index(op.f('ix_social_comments_platform'), 'social_comments', ['platform'], unique=False)
    op.create_index(op.f('ix_social_comments_risk_status'), 'social_comments', ['risk_status'], unique=False)
    op.create_index(op.f('ix_social_comments_source_id'), 'social_comments', ['source_id'], unique=False)
    op.create_index(op.f('ix_social_comments_status'), 'social_comments', ['status'], unique=False)
    op.create_table('voice_clone_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('training_job_id', sa.String(length=32), nullable=True),
    sa.Column('cloned_voice_name', sa.String(length=120), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('external_voice_id', sa.String(length=160), nullable=False),
    sa.Column('preview_audio_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('sample_minutes', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['voice_profiles.id'], ),
    sa.ForeignKeyConstraint(['training_job_id'], ['voice_training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_clone_records_profile_id'), 'voice_clone_records', ['profile_id'], unique=False)
    op.create_index(op.f('ix_voice_clone_records_status'), 'voice_clone_records', ['status'], unique=False)
    op.create_index(op.f('ix_voice_clone_records_training_job_id'), 'voice_clone_records', ['training_job_id'], unique=False)
    op.create_table('comment_lead_conversions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('comment_id', sa.String(length=32), nullable=False),
    sa.Column('lead_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['social_comments.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['merchant_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_lead_conversions_action'), 'comment_lead_conversions', ['action'], unique=False)
    op.create_index(op.f('ix_comment_lead_conversions_comment_id'), 'comment_lead_conversions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_lead_conversions_lead_id'), 'comment_lead_conversions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_comment_lead_conversions_status'), 'comment_lead_conversions', ['status'], unique=False)
    op.create_table('dm_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('external_message_id', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['dm_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_messages_conversation_id'), 'dm_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_dm_messages_direction'), 'dm_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_dm_messages_status'), 'dm_messages', ['status'], unique=False)
    op.create_table('follow_up_work_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('last_note', sa.Text(), nullable=False),
    sa.Column('closed_reason', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['intent_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_work_orders_customer_id'), 'follow_up_work_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_follow_up_work_orders_owner_name'), 'follow_up_work_orders', ['owner_name'], unique=False)
    op.create_index(op.f('ix_follow_up_work_orders_priority'), 'follow_up_work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_follow_up_work_orders_status'), 'follow_up_work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_follow_up_work_orders_title'), 'follow_up_work_orders', ['title'], unique=False)
    op.create_table('intent_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('lead_id', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('intent_level', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=240), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('need_handoff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['intent_customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['merchant_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_events_channel'), 'intent_events', ['channel'], unique=False)
    op.create_index(op.f('ix_intent_events_customer_id'), 'intent_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_intent_events_intent_level'), 'intent_events', ['intent_level'], unique=False)
    op.create_index(op.f('ix_intent_events_lead_id'), 'intent_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_intent_events_need_handoff'), 'intent_events', ['need_handoff'], unique=False)
    op.create_index(op.f('ix_intent_events_source_record_id'), 'intent_events', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_intent_events_source_type'), 'intent_events', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_events_source_type'), table_name='intent_events')
    op.drop_index(op.f('ix_intent_events_source_record_id'), table_name='intent_events')
    op.drop_index(op.f('ix_intent_events_need_handoff'), table_name='intent_events')
    op.drop_index(op.f('ix_intent_events_lead_id'), table_name='intent_events')
    op.drop_index(op.f('ix_intent_events_intent_level'), table_name='intent_events')
    op.drop_index(op.f('ix_intent_events_customer_id'), table_name='intent_events')
    op.drop_index(op.f('ix_intent_events_channel'), table_name='intent_events')
    op.drop_table('intent_events')
    op.drop_index(op.f('ix_follow_up_work_orders_title'), table_name='follow_up_work_orders')
    op.drop_index(op.f('ix_follow_up_work_orders_status'), table_name='follow_up_work_orders')
    op.drop_index(op.f('ix_follow_up_work_orders_priority'), table_name='follow_up_work_orders')
    op.drop_index(op.f('ix_follow_up_work_orders_owner_name'), table_name='follow_up_work_orders')
    op.drop_index(op.f('ix_follow_up_work_orders_customer_id'), table_name='follow_up_work_orders')
    op.drop_table('follow_up_work_orders')
    op.drop_index(op.f('ix_dm_messages_status'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_direction'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_messages_conversation_id'), table_name='dm_messages')
    op.drop_table('dm_messages')
    op.drop_index(op.f('ix_comment_lead_conversions_status'), table_name='comment_lead_conversions')
    op.drop_index(op.f('ix_comment_lead_conversions_lead_id'), table_name='comment_lead_conversions')
    op.drop_index(op.f('ix_comment_lead_conversions_comment_id'), table_name='comment_lead_conversions')
    op.drop_index(op.f('ix_comment_lead_conversions_action'), table_name='comment_lead_conversions')
    op.drop_table('comment_lead_conversions')
    op.drop_index(op.f('ix_voice_clone_records_training_job_id'), table_name='voice_clone_records')
    op.drop_index(op.f('ix_voice_clone_records_status'), table_name='voice_clone_records')
    op.drop_index(op.f('ix_voice_clone_records_profile_id'), table_name='voice_clone_records')
    op.drop_table('voice_clone_records')
    op.drop_index(op.f('ix_social_comments_status'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_source_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_risk_status'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_platform'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_intent_score'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_intent_level'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_external_comment_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_city'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_category'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_author_name'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_index(op.f('ix_intent_customers_platform'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_owner_name'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_need_handoff'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_merchant_name'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_lead_id'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_intent_level'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_follow_status'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_dnc_status'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_city'), table_name='intent_customers')
    op.drop_index(op.f('ix_intent_customers_category'), table_name='intent_customers')
    op.drop_table('intent_customers')
    op.drop_index(op.f('ix_dm_conversations_task_id'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_status'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_platform'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_merchant_name'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_lead_id'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_intent_level'), table_name='dm_conversations')
    op.drop_index(op.f('ix_dm_conversations_account_id'), table_name='dm_conversations')
    op.drop_table('dm_conversations')
    op.drop_index(op.f('ix_voice_usage_records_task_id'), table_name='voice_usage_records')
    op.drop_index(op.f('ix_voice_usage_records_scenario'), table_name='voice_usage_records')
    op.drop_index(op.f('ix_voice_usage_records_result'), table_name='voice_usage_records')
    op.drop_index(op.f('ix_voice_usage_records_profile_id'), table_name='voice_usage_records')
    op.drop_index(op.f('ix_voice_usage_records_fallback_used'), table_name='voice_usage_records')
    op.drop_table('voice_usage_records')
    op.drop_index(op.f('ix_voice_training_jobs_status'), table_name='voice_training_jobs')
    op.drop_index(op.f('ix_voice_training_jobs_profile_id'), table_name='voice_training_jobs')
    op.drop_table('voice_training_jobs')
    op.drop_index(op.f('ix_voice_samples_quality_status'), table_name='voice_samples')
    op.drop_index(op.f('ix_voice_samples_profile_id'), table_name='voice_samples')
    op.drop_table('voice_samples')
    op.drop_index(op.f('ix_knowledge_base_items_title'), table_name='knowledge_base_items')
    op.drop_index(op.f('ix_knowledge_base_items_status'), table_name='knowledge_base_items')
    op.drop_index(op.f('ix_knowledge_base_items_source_suggestion_id'), table_name='knowledge_base_items')
    op.drop_index(op.f('ix_knowledge_base_items_category'), table_name='knowledge_base_items')
    op.drop_table('knowledge_base_items')
    op.drop_index(op.f('ix_comment_intercept_sources_sync_status'), table_name='comment_intercept_sources')
    op.drop_index(op.f('ix_comment_intercept_sources_source_type'), table_name='comment_intercept_sources')
    op.drop_index(op.f('ix_comment_intercept_sources_platform'), table_name='comment_intercept_sources')
    op.drop_index(op.f('ix_comment_intercept_sources_owner_account_id'), table_name='comment_intercept_sources')
    op.drop_index(op.f('ix_comment_intercept_sources_name'), table_name='comment_intercept_sources')
    op.drop_table('comment_intercept_sources')
    op.drop_index(op.f('ix_voice_profiles_status'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_scenario'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_owner_name'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_name'), table_name='voice_profiles')
    op.drop_index(op.f('ix_voice_profiles_authorization_status'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_system_settings_status'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_sensitive'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_label'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_item_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_group_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_audit_logs_target_type'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_target_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_actor'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_action'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_report_exports_status'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_requester'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_report_type'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_learning_suggestions_title'), table_name='learning_suggestions')
    op.drop_index(op.f('ix_learning_suggestions_target_type'), table_name='learning_suggestions')
    op.drop_index(op.f('ix_learning_suggestions_status'), table_name='learning_suggestions')
    op.drop_index(op.f('ix_learning_suggestions_source_type'), table_name='learning_suggestions')
    op.drop_index(op.f('ix_learning_suggestions_source_record_id'), table_name='learning_suggestions')
    op.drop_table('learning_suggestions')
    op.drop_index(op.f('ix_learning_experiments_target_type'), table_name='learning_experiments')
    op.drop_index(op.f('ix_learning_experiments_status'), table_name='learning_experiments')
    op.drop_index(op.f('ix_learning_experiments_name'), table_name='learning_experiments')
    op.drop_table('learning_experiments')
    op.drop_index(op.f('ix_dm_templates_platform'), table_name='dm_templates')
    op.drop_index(op.f('ix_dm_templates_name'), table_name='dm_templates')
    op.drop_table('dm_templates')
    op.drop_index(op.f('ix_dm_platform_configs_platform'), table_name='dm_platform_configs')
    op.drop_table('dm_platform_configs')
    op.drop_index(op.f('ix_dm_accounts_status'), table_name='dm_accounts')
    op.drop_index(op.f('ix_dm_accounts_session_status'), table_name='dm_accounts')
    op.drop_index(op.f('ix_dm_accounts_risk_status'), table_name='dm_accounts')
    op.drop_index(op.f('ix_dm_accounts_platform'), table_name='dm_accounts')
    op.drop_index(op.f('ix_dm_accounts_account_name'), table_name='dm_accounts')
    op.drop_table('dm_accounts')
    # ### end Alembic commands ###
