"""expand system setting value type

Revision ID: 0ea9dfe9e60d
Revises: a2873f567b8c
Create Date: 2026-07-06 17:57:17.909046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea9dfe9e60d'
down_revision: Union[str, Sequence[str], None] = 'a2873f567b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'value_type',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=240),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'value_type',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
