"""add lead provider configs

Revision ID: 1ec880e15b51
Revises: e0c49bbfb41d
Create Date: 2026-06-29 16:50:33.362783

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec880e15b51'
down_revision: Union[str, Sequence[str], None] = 'e0c49bbfb41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_provider_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('service_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('qps_limit', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_provider_configs_enabled'), 'lead_provider_configs', ['enabled'], unique=False)
    op.create_index(op.f('ix_lead_provider_configs_provider'), 'lead_provider_configs', ['provider'], unique=True)
    provider_configs = sa.table(
        "lead_provider_configs",
        sa.column("id", sa.String),
        sa.column("provider", sa.String),
        sa.column("name", sa.String),
        sa.column("api_key", sa.String),
        sa.column("secret_key", sa.String),
        sa.column("service_url", sa.String),
        sa.column("enabled", sa.Boolean),
        sa.column("daily_limit", sa.Integer),
        sa.column("qps_limit", sa.Integer),
        sa.column("remark", sa.Text),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(
        provider_configs,
        [
            {
                "id": "provider_amap",
                "provider": "amap",
                "name": "高德地图",
                "api_key": None,
                "secret_key": None,
                "service_url": "https://restapi.amap.com/v3/place/text",
                "enabled": True,
                "daily_limit": None,
                "qps_limit": None,
                "remark": "填写高德地图服务密钥后，可用于地图点位采集。",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "provider_baidu",
                "provider": "baidu",
                "name": "百度地图",
                "api_key": None,
                "secret_key": None,
                "service_url": "https://api.map.baidu.com/place/v3/region",
                "enabled": False,
                "daily_limit": None,
                "qps_limit": None,
                "remark": "填写百度地图访问密钥后，可用于地图点位采集。",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "provider_tencent",
                "provider": "tencent",
                "name": "腾讯位置服务",
                "api_key": None,
                "secret_key": None,
                "service_url": "https://apis.map.qq.com/ws/place/v1/search",
                "enabled": False,
                "daily_limit": None,
                "qps_limit": None,
                "remark": "腾讯位置服务配置已保留，前台暂时隐藏，确认配额后再启用。",
                "created_at": now,
                "updated_at": now,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_provider_configs_provider'), table_name='lead_provider_configs')
    op.drop_index(op.f('ix_lead_provider_configs_enabled'), table_name='lead_provider_configs')
    op.drop_table('lead_provider_configs')
    # ### end Alembic commands ###
