"""add collection tenant scope

Revision ID: 56f3c625e544
Revises: 1ec880e15b51
Create Date: 2026-06-29 20:01:30.227012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f3c625e544'
down_revision: Union[str, Sequence[str], None] = '1ec880e15b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_collection_tasks', sa.Column('owner_user_id', sa.String(length=32), nullable=True))
    op.add_column('lead_collection_tasks', sa.Column('created_by_user_id', sa.String(length=32), nullable=True))
    op.execute(
        """
        UPDATE lead_collection_tasks
        SET
            owner_user_id = (
                SELECT id FROM users
                ORDER BY last_login_at DESC NULLS LAST, created_at ASC
                LIMIT 1
            ),
            created_by_user_id = (
                SELECT id FROM users
                ORDER BY last_login_at DESC NULLS LAST, created_at ASC
                LIMIT 1
            )
        WHERE owner_user_id IS NULL
          AND EXISTS (SELECT 1 FROM users)
        """,
    )
    op.execute(
        """
        UPDATE merchant_leads
        SET
            owner_user_id = (
                SELECT id FROM users
                ORDER BY last_login_at DESC NULLS LAST, created_at ASC
                LIMIT 1
            ),
            created_by_user_id = COALESCE(
                created_by_user_id,
                (
                    SELECT id FROM users
                    ORDER BY last_login_at DESC NULLS LAST, created_at ASC
                    LIMIT 1
                )
            )
        WHERE owner_user_id IS NULL
          AND EXISTS (SELECT 1 FROM users)
        """,
    )
    op.create_index(op.f('ix_lead_collection_tasks_owner_user_id'), 'lead_collection_tasks', ['owner_user_id'], unique=False)
    op.create_foreign_key(
        'fk_lead_collection_tasks_created_by_user_id_users',
        'lead_collection_tasks',
        'users',
        ['created_by_user_id'],
        ['id'],
    )
    op.create_foreign_key(
        'fk_lead_collection_tasks_owner_user_id_users',
        'lead_collection_tasks',
        'users',
        ['owner_user_id'],
        ['id'],
    )
    op.add_column('raw_lead_records', sa.Column('owner_user_id', sa.String(length=32), nullable=True))
    op.execute(
        """
        UPDATE raw_lead_records AS raw
        SET owner_user_id = task.owner_user_id
        FROM lead_collection_tasks AS task
        WHERE raw.task_id = task.id
          AND raw.owner_user_id IS NULL
        """,
    )
    op.drop_constraint(op.f('uq_raw_lead_records_provider_poi'), 'raw_lead_records', type_='unique')
    op.create_index(op.f('ix_raw_lead_records_owner_user_id'), 'raw_lead_records', ['owner_user_id'], unique=False)
    op.create_unique_constraint('uq_raw_lead_records_owner_provider_poi', 'raw_lead_records', ['owner_user_id', 'provider', 'source_poi_id'])
    op.create_foreign_key(
        'fk_raw_lead_records_owner_user_id_users',
        'raw_lead_records',
        'users',
        ['owner_user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_raw_lead_records_owner_user_id_users', 'raw_lead_records', type_='foreignkey')
    op.drop_constraint('uq_raw_lead_records_owner_provider_poi', 'raw_lead_records', type_='unique')
    op.drop_index(op.f('ix_raw_lead_records_owner_user_id'), table_name='raw_lead_records')
    op.create_unique_constraint(op.f('uq_raw_lead_records_provider_poi'), 'raw_lead_records', ['provider', 'source_poi_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('raw_lead_records', 'owner_user_id')
    op.drop_constraint('fk_lead_collection_tasks_owner_user_id_users', 'lead_collection_tasks', type_='foreignkey')
    op.drop_constraint('fk_lead_collection_tasks_created_by_user_id_users', 'lead_collection_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_lead_collection_tasks_owner_user_id'), table_name='lead_collection_tasks')
    op.drop_column('lead_collection_tasks', 'created_by_user_id')
    op.drop_column('lead_collection_tasks', 'owner_user_id')
    # ### end Alembic commands ###
