"""add collection async mode

Revision ID: 6fe1608c0cbf
Revises: 076d9f21b4e3
Create Date: 2026-07-05 19:28:43.797011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe1608c0cbf'
down_revision: Union[str, Sequence[str], None] = '076d9f21b4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'lead_collection_runs',
        sa.Column('collection_mode', sa.String(length=40), nullable=False, server_default='discovery'),
    )
    op.add_column(
        'lead_collection_runs',
        sa.Column('updated_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.create_index(op.f('ix_lead_collection_runs_collection_mode'), 'lead_collection_runs', ['collection_mode'], unique=False)
    op.add_column(
        'lead_collection_tasks',
        sa.Column('collection_mode', sa.String(length=40), nullable=False, server_default='discovery'),
    )
    op.create_index(op.f('ix_lead_collection_tasks_collection_mode'), 'lead_collection_tasks', ['collection_mode'], unique=False)
    op.alter_column('lead_collection_runs', 'collection_mode', server_default=None)
    op.alter_column('lead_collection_runs', 'updated_count', server_default=None)
    op.alter_column('lead_collection_tasks', 'collection_mode', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_collection_tasks_collection_mode'), table_name='lead_collection_tasks')
    op.drop_column('lead_collection_tasks', 'collection_mode')
    op.drop_index(op.f('ix_lead_collection_runs_collection_mode'), table_name='lead_collection_runs')
    op.drop_column('lead_collection_runs', 'updated_count')
    op.drop_column('lead_collection_runs', 'collection_mode')
    # ### end Alembic commands ###
