"""add call recordings

Revision ID: a74e262a074e
Revises: 20260710_0021
Create Date: 2026-07-10 15:33:42.126035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74e262a074e'
down_revision: Union[str, Sequence[str], None] = '20260710_0021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('recording_path', sa.Text(), nullable=True))
    op.add_column(
        'call_records',
        sa.Column('recording_status', sa.String(length=40), server_default='unavailable', nullable=False),
    )
    op.add_column('call_records', sa.Column('recording_mime_type', sa.String(length=80), nullable=True))
    op.add_column(
        'call_records',
        sa.Column('recording_size_bytes', sa.Integer(), server_default='0', nullable=False),
    )
    op.create_index(op.f('ix_call_records_recording_status'), 'call_records', ['recording_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_records_recording_status'), table_name='call_records')
    op.drop_column('call_records', 'recording_size_bytes')
    op.drop_column('call_records', 'recording_mime_type')
    op.drop_column('call_records', 'recording_status')
    op.drop_column('call_records', 'recording_path')
    # ### end Alembic commands ###
