"""add users roles and lead fields

Revision ID: b8538627302e
Revises: 20260628_0001
Create Date: 2026-06-29 09:58:37.050032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8538627302e'
down_revision: Union[str, Sequence[str], None] = '20260628_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.add_column('merchant_leads', sa.Column('contact_title', sa.String(length=80), nullable=True))
    op.add_column('merchant_leads', sa.Column('wechat_id', sa.String(length=80), nullable=True))
    op.add_column('merchant_leads', sa.Column('platform_homepage_url', sa.String(length=500), nullable=True))
    op.add_column('merchant_leads', sa.Column('province', sa.String(length=40), nullable=True))
    op.add_column('merchant_leads', sa.Column('district', sa.String(length=80), nullable=True))
    op.add_column('merchant_leads', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column(
        'merchant_leads',
        sa.Column('follow_up_status', sa.String(length=40), server_default='未跟进', nullable=False),
    )
    op.add_column('merchant_leads', sa.Column('remark', sa.Text(), nullable=True))
    op.add_column('merchant_leads', sa.Column('owner_user_id', sa.String(length=32), nullable=True))
    op.add_column('merchant_leads', sa.Column('created_by_user_id', sa.String(length=32), nullable=True))
    op.add_column('merchant_leads', sa.Column('last_contact_at', sa.DateTime(), nullable=True))
    op.add_column('merchant_leads', sa.Column('next_follow_up_at', sa.DateTime(), nullable=True))
    op.add_column(
        'merchant_leads',
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    )
    op.create_index(op.f('ix_merchant_leads_follow_up_status'), 'merchant_leads', ['follow_up_status'], unique=False)
    op.create_index(op.f('ix_merchant_leads_owner_user_id'), 'merchant_leads', ['owner_user_id'], unique=False)
    op.create_foreign_key(
        'fk_merchant_leads_owner_user_id_users',
        'merchant_leads',
        'users',
        ['owner_user_id'],
        ['id'],
    )
    op.create_foreign_key(
        'fk_merchant_leads_created_by_user_id_users',
        'merchant_leads',
        'users',
        ['created_by_user_id'],
        ['id'],
    )
    op.alter_column('merchant_leads', 'follow_up_status', server_default=None)
    op.alter_column('merchant_leads', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_merchant_leads_created_by_user_id_users', 'merchant_leads', type_='foreignkey')
    op.drop_constraint('fk_merchant_leads_owner_user_id_users', 'merchant_leads', type_='foreignkey')
    op.drop_index(op.f('ix_merchant_leads_owner_user_id'), table_name='merchant_leads')
    op.drop_index(op.f('ix_merchant_leads_follow_up_status'), table_name='merchant_leads')
    op.drop_column('merchant_leads', 'updated_at')
    op.drop_column('merchant_leads', 'next_follow_up_at')
    op.drop_column('merchant_leads', 'last_contact_at')
    op.drop_column('merchant_leads', 'created_by_user_id')
    op.drop_column('merchant_leads', 'owner_user_id')
    op.drop_column('merchant_leads', 'remark')
    op.drop_column('merchant_leads', 'follow_up_status')
    op.drop_column('merchant_leads', 'address')
    op.drop_column('merchant_leads', 'district')
    op.drop_column('merchant_leads', 'province')
    op.drop_column('merchant_leads', 'platform_homepage_url')
    op.drop_column('merchant_leads', 'wechat_id')
    op.drop_column('merchant_leads', 'contact_title')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
