"""add browser sessions

Revision ID: d70c376a85f7
Revises: d8c5ffd600e4
Create Date: 2026-06-30 16:38:01.784879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70c376a85f7'
down_revision: Union[str, Sequence[str], None] = 'd8c5ffd600e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_browser_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('login_url', sa.String(length=500), nullable=False),
    sa.Column('home_url', sa.String(length=500), nullable=False),
    sa.Column('profile_dir', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('login_process_id', sa.Integer(), nullable=True),
    sa.Column('last_login_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_browser_sessions_provider'), 'platform_browser_sessions', ['provider'], unique=True)
    op.create_index(op.f('ix_platform_browser_sessions_status'), 'platform_browser_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_browser_sessions_status'), table_name='platform_browser_sessions')
    op.drop_index(op.f('ix_platform_browser_sessions_provider'), table_name='platform_browser_sessions')
    op.drop_table('platform_browser_sessions')
    # ### end Alembic commands ###
