"""add lead collection tables

Revision ID: e0c49bbfb41d
Revises: 20260629_0003
Create Date: 2026-06-29 16:43:39.136407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c49bbfb41d'
down_revision: Union[str, Sequence[str], None] = '20260629_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_collection_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('target_per_keyword', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_run_status', sa.String(length=40), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_collection_tasks_created_at'), 'lead_collection_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_collection_tasks_name'), 'lead_collection_tasks', ['name'], unique=False)
    op.create_index(op.f('ix_lead_collection_tasks_provider'), 'lead_collection_tasks', ['provider'], unique=False)
    op.create_index(op.f('ix_lead_collection_tasks_status'), 'lead_collection_tasks', ['status'], unique=False)
    op.create_table('lead_collection_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['lead_collection_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_collection_runs_provider'), 'lead_collection_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_lead_collection_runs_started_at'), 'lead_collection_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_lead_collection_runs_status'), 'lead_collection_runs', ['status'], unique=False)
    op.create_index(op.f('ix_lead_collection_runs_task_id'), 'lead_collection_runs', ['task_id'], unique=False)
    op.create_table('raw_lead_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('lead_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('source_poi_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.String(length=40), nullable=True),
    sa.Column('import_status', sa.String(length=40), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['merchant_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['lead_collection_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['lead_collection_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'source_poi_id', name='uq_raw_lead_records_provider_poi')
    )
    op.create_index(op.f('ix_raw_lead_records_city'), 'raw_lead_records', ['city'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_created_at'), 'raw_lead_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_import_status'), 'raw_lead_records', ['import_status'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_name'), 'raw_lead_records', ['name'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_provider'), 'raw_lead_records', ['provider'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_run_id'), 'raw_lead_records', ['run_id'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_source_poi_id'), 'raw_lead_records', ['source_poi_id'], unique=False)
    op.create_index(op.f('ix_raw_lead_records_task_id'), 'raw_lead_records', ['task_id'], unique=False)
    op.add_column('merchant_leads', sa.Column('source_poi_id', sa.String(length=120), nullable=True))
    op.add_column('merchant_leads', sa.Column('longitude', sa.String(length=40), nullable=True))
    op.add_column('merchant_leads', sa.Column('latitude', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_merchant_leads_source_poi_id'), 'merchant_leads', ['source_poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_leads_source_poi_id'), table_name='merchant_leads')
    op.drop_column('merchant_leads', 'latitude')
    op.drop_column('merchant_leads', 'longitude')
    op.drop_column('merchant_leads', 'source_poi_id')
    op.drop_index(op.f('ix_raw_lead_records_task_id'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_source_poi_id'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_run_id'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_provider'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_name'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_import_status'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_created_at'), table_name='raw_lead_records')
    op.drop_index(op.f('ix_raw_lead_records_city'), table_name='raw_lead_records')
    op.drop_table('raw_lead_records')
    op.drop_index(op.f('ix_lead_collection_runs_task_id'), table_name='lead_collection_runs')
    op.drop_index(op.f('ix_lead_collection_runs_status'), table_name='lead_collection_runs')
    op.drop_index(op.f('ix_lead_collection_runs_started_at'), table_name='lead_collection_runs')
    op.drop_index(op.f('ix_lead_collection_runs_provider'), table_name='lead_collection_runs')
    op.drop_table('lead_collection_runs')
    op.drop_index(op.f('ix_lead_collection_tasks_status'), table_name='lead_collection_tasks')
    op.drop_index(op.f('ix_lead_collection_tasks_provider'), table_name='lead_collection_tasks')
    op.drop_index(op.f('ix_lead_collection_tasks_name'), table_name='lead_collection_tasks')
    op.drop_index(op.f('ix_lead_collection_tasks_created_at'), table_name='lead_collection_tasks')
    op.drop_table('lead_collection_tasks')
    # ### end Alembic commands ###
