[general]
enabled = yes
webenabled = no
port = 5038
bindaddr = 127.0.0.1

[ai_acq]
secret = REPLACE_AMI_PASSWORD
read = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate,message
write = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate,message
